### PR TITLE
(GH-22) Move generic code to Cake.Tfs addin

### LINKED ISSUE #22: Move generic TFS code to separate addin
We should move generic TFS code (like authentication, voting) to a separate addin. 

See https://github.com/cake-contrib/addin-requests/issues/8

### PR DESCRIPTION
**Pull request by yansklyarenko**
Consume the changes from `Cake.Tfs` as the code is migrated. The `Cake.Tfs` package reference version is not modified deliberately until it is known when released.

Fixed #22.

### CODE REVIEW

**Comment by pascalberger** [comment]
The functionality to retrieve modified files (https://github.com/cake-contrib/Cake.Tfs/pull/55) is already released with Cake.Tfs 0.2.4. So, if you want we can split this PR and have the first part already merged.

**Comment by yansklyarenko** [comment]
@pascalberger Yes, makes sense. I'll create a new PR consuming just the functionality to retrieve modified files and then rebase this one later. Thanks for the hint!

**Comment by yansklyarenko** [comment]
@pascalberger Now this one is ready for review. I had to bump the version of Cake.Tfs here to pass the build. I understand one more rebase is required once the appropriate branch from the bot is merged.

**Comment by pascalberger** [comment]
@yansklyarenko I canceled the PR from the bot, so that we can bump version of Cake.Tfs here.

**Comment by pascalberger** [comment]
@yansklyarenko your changes have been merged, thanks for your contribution 👍

**Pull request merged**
